<?php

// $Id$ 

/**
 * @file 
 */

/**
 * Implementation of hook_block() 
 */
function parliamentwatch_internals_block($op='list', $delta=0, $edit=array()) {
  switch ($op) {
    case 'list':

    case 'view':

    case 'configure':

    case 'save':
  }
}

/**
 * Implementation of hook_help() 
 */
function parliamentwatch_internals_help($path, $arg) {
  
}

/**
 * Implementation of hook_cron() 
 */
function parliamentwatch_internals_cron() {
  if (db_set_active('openemm')) {
    $query = db_select("aw_abgeordnete", "aw");
    $num_rows = $query->countQuery()->execute()->fetchField();
    db_set_active();
    variable_set('newsletter_abo_count', $num_rows);
    drupal_set_message($num_rows . " rows", $type = 'status');
  }
}
