<?php
/**
 * @file
 * field_comment_newsletter_subscription.features.field.inc
 */

/**
 * Implements hook_field_default_fields().
 */
function field_comment_newsletter_subscription_field_default_fields() {
  $fields = array();

  // Exported field: 'comment-comment_node_blogpost-field_newsletter_subscribe'
  $fields['comment-comment_node_blogpost-field_newsletter_subscribe'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '-1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_newsletter_subscribe',
      'foreign keys' => array(),
      'indexes' => array(
        'value' => array(
          0 => 'value',
        ),
      ),
      'module' => 'list',
      'settings' => array(
        'allowed_values' => array(
          0 => '',
          1 => '',
        ),
        'allowed_values_function' => '',
      ),
      'translatable' => '0',
      'type' => 'list_boolean',
    ),
    'field_instance' => array(
      'bundle' => 'comment_node_blogpost',
      'default_value' => array(
        0 => array(
          'value' => 1,
        ),
      ),
      'deleted' => '0',
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => '2',
        ),
      ),
      'ds_extras_field_template' => '',
      'entity_type' => 'comment',
      'field_name' => 'field_newsletter_subscribe',
      'label' => 'Newsletter bestellen',
      'required' => 0,
      'settings' => array(
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'options',
        'settings' => array(
          'display_label' => 1,
        ),
        'type' => 'options_onoff',
        'weight' => '3',
      ),
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Newsletter bestellen');

  return $fields;
}
