<?php

/*
 * Implement hook_permission().
 */

function views_memberships_permission() {
  return array(
      'access migration' => array(
          'title' => t('Access Migration'),
          'description' => t('Access Migration'),
      )
  );
}

/*
 * Implement hook_menu()
 */

function migrate_memberships_menu() {
  $items = array();
  $items['admin/content/migrate/migrate_memberships'] = array(
      'page callback' => 'migrate_memberships_callback',
      'title' => 'Migrate Memberships',
      'access arguments' => array('access migration'),
      'type' => MENU_LOCAL_TASK,
  );
  return $items;
}

/*
 * Implement migrate_memberships_callback()
 */

function migrate_memberships_callback() {
  return drupal_get_form('migrate_memberships_form');
}

/*
 * Implement migrate_memberships_form()
 */

function migrate_memberships_form($form, &$form_state) {
  $form['submit'] = array(
      '#type' => 'submit',
      '#value' => t('Migrate Memberships')
  );
  return $form;
}

/*
 * Implement migrate_memberships_form_submit()
 */

function migrate_memberships_form_submit($form, &$form_state) {

  // Get instance of previous migration
  $migration_user = MigrationBase::getInstance('politician');
  $migration_committee = MigrationBase::getInstance('committeeTerm');
  $migration_constituency = MigrationBase::getInstance('constituencyTerm');
  $migration_parliament = MigrationBase::getInstance('parliamentTerm');

  // Load all users with specific role (politician)
  $query = db_select('users', 'u');
  $query->join('users_roles', 'ur', 'u.uid = ur.uid');
  $query->join('role', 'r', 'ur.rid = r.rid');
  $query->fields('u', array('uid'));
  $query->condition('r.name', 'Politician', '=');
  //$query->range(0,10);
  $result = $query->execute();
  $result_count = $query->countQuery()->execute()->fetchField();

  drupal_set_message("checking $result_count politicians");

  // Loop through politicians
  $count_memberships_created = array('committee' => 0, 'constituency' => 0, 'parliament' => 0);
  while ($row = $result->fetchObject()) {
    
    // Load userdata
    $user = user_load($row->uid);
    // Get mapping to legacy user
    $migration_mapping = $migration_user->getMap()->lookupSourceID(array($user->uid));
    $legacy_uid = $migration_mapping['sourceid1'];

    // Load legacy memberships for migration
    $legacy_query = Database::getConnection('default', 'parlamentwatch')
            ->select('legacy_membership', 'm');
    $legacy_query->fields('m');
    $legacy_query->condition('m.uid', $legacy_uid, '=');
    $legacy_result = $legacy_query->execute();

    // Loop through legacy memberships
    while ($legacy_membership = $legacy_result->fetchObject()) {

      // Get destination term id by loading migration data
      switch ($legacy_membership->type) {
        case 'committee':
          $migration_mapping = $migration_committee->getMap()->lookupDestinationID(array($legacy_membership->gid));
		  $dest_field = &$user->field_user_commitee['und'];
          break;
        case 'constituency':
          $migration_mapping = $migration_constituency->getMap()->lookupDestinationID(array($legacy_membership->gid));
		  $dest_field = &$user->field_user_constituency['und'];
          break;
        case 'parliament':
          $migration_mapping = $migration_parliament->getMap()->lookupDestinationID(array($legacy_membership->gid));
		  $dest_field = &$user->field_user_parliament['und'];
          break;
      }

     // Check if target term is already migrated
      $dest_tid = $migration_mapping['destid1'];
      if ($dest_tid) {

		// Field value must be an array
		if(!is_array($dest_field)){
			$dest_field = array();
		}

		// Check if term is already in field
		$term_exists = false;
		foreach($dest_field as $a_term){
			if($a_term['tid'] == $dest_tid){
				$term_exists = true;
			}
		}
		if(!$term_exists){

			// Add term to field
			array_push($dest_field, array('tid' => $dest_tid));

			// For output
		    $count_memberships_created[$legacy_membership->type]++;
		}
      }
    }

	// Finally save the user
    $user->revision = 0;
    $user = user_save($user);
  }

  // Output
  foreach ($count_memberships_created as $type => $count) {
    drupal_set_message("$count memberships of type $type created!");
  }
}

