<?php

/*
 * Implement hook_permission().
 */

function views_memberships_permission() {
  return array(
      'access migration' => array(
          'title' => t('Access Migration'),
          'description' => t('Access Migration'),
      )
  );
}

/*
 * Implement hook_menu()
 */

function migrate_memberships_menu() {
  $items = array();
  $items['admin/content/migrate/migrate_memberships'] = array(
      'page callback' => 'migrate_memberships_callback',
      'title' => 'Migrate Memberships',
      'access arguments' => array('access migration'),
      'type' => MENU_LOCAL_TASK,
  );
  return $items;
}

/*
 * Implement migrate_memberships_callback()
 */

function migrate_memberships_callback() {
  return drupal_get_form('migrate_memberships_form');
}

/*
 * Implement migrate_memberships_form()
 */

function migrate_memberships_form($form, &$form_state) {
  $form['submit'] = array(
      '#type' => 'submit',
      '#value' => t('Migrate Memberships')
  );
  return $form;
}

/*
 * Implement migrate_memberships_form_submit()
 */

function migrate_memberships_form_submit($form, &$form_state) {

  // Get instance of previous migration
  $migration_user = MigrationBase::getInstance('politician');
  $migration_committee = MigrationBase::getInstance('committee');
  $migration_constituency = MigrationBase::getInstance('constituency');
  $migration_party = MigrationBase::getInstance('party');

  // Load all users with specific role (politician)
  $query = db_select('users', 'u');
  $query->join('users_roles', 'ur', 'u.uid = ur.uid');
  $query->join('role', 'r', 'ur.rid = r.rid');
  $query->fields('u', array('uid'));
  $query->condition('r.name', 'Politician', '=');
  $result = $query->execute();
  $result_count = $query->countQuery()->execute()->fetchField();

  drupal_set_message("checking $result_count politicians");

  // Loop through politicians
  $count_memberships_created = array('committee' => 0, 'constituency' => 0, 'party' => 0);
  while ($row = $result->fetchObject()) {

    // Load userdata
    $user = user_load($row->uid);

    // Get mapping to legacy user
    $migration_mapping = $migration_user->getMap()->lookupSourceID(array($user->uid));
    $legacy_uid = $migration_mapping['sourceid1'];

    // Load legacy memberships for migration
    $legacy_query = Database::getConnection('default', 'parlamentwatch')
            ->select('legacy_membership', 'm');
    $legacy_query->fields('m');
    $legacy_query->condition('m.uid', $legacy_uid, '=');
    $legacy_result = $legacy_query->execute();

    // Loop through legacy memberships
    while ($legacy_membership = $legacy_result->fetchObject()) {

      // Get destination group id by loading migration data
      switch ($legacy_membership->type) {
        case 'committee':
          $migration_mapping = $migration_committee->getMap()->lookupDestinationID(array($legacy_membership->gid));
          $dest_gid = $migration_mapping['destid1'];
          break;
        case 'constituency':
          $migration_mapping = $migration_constituency->getMap()->lookupDestinationID(array($legacy_membership->gid));
          $dest_gid = $migration_mapping['destid1'];
          break;
        case 'party':
          $migration_mapping = $migration_party->getMap()->lookupDestinationID(array($legacy_membership->gid));
          $dest_gid = $migration_mapping['destid1'];
          break;
      }

      // Check if membership exists
      if ($dest_gid) {
        $check_query = db_select('{og_membership}', 'm');
        $check_query->condition('m.etid', $user->uid, '=');
        $check_query->condition('m.entity_type', 'user', '=');
        $check_query->condition('m.gid', $dest_gid, '=');
        $check_count = $check_query->countQuery()->execute()->fetchField();

        // Creating membership
        if ($check_count == 0) {
          $membership = og_membership_create($dest_gid, 'user', $user->uid);
          og_membership_save($membership);
          $og = og_load($dest_gid);
          $l_name = l($user->name, "user/$user->uid");
          $l_group = l($og->label, "node/$dest_gid");
          drupal_set_message("adding $l_name to $l_group");
          $count_memberships_created[$legacy_membership->type]++;
        }
      }
    }
  }
  foreach ($count_memberships_created as $type => $count) {
    drupal_set_message("$count memberships of type $type created!");
  }
}

