<?php

/**
 * @file
 * Provides an interface for developers to query the available data.
 */

/**
 * Implements hook_services_resources().
 */
function pw_api_services_resources() {
  return array(
    'parliament' => array(
      'retrieve' => array(
        'help' => 'Retrieves a parliament',
        'file' => array('file' => 'inc', 'module' => 'pw_api'),
        'callback' => 'pw_api_parliament_retrieve',
        'access callback' => 'user_access',
        'access arguments' => array('access content'), // TODO: Figure out the right permission
        'access arguments append' => FALSE,
        'args' => array(
          array(
            'name' => 'id',
            'type' => 'int',
            'description' => 'The id of the parliament to get',
            'source' => array('path' => 0),
            'optional' => FALSE,
          ),
        ),
      ),
      'index' => array(
        'help' => 'Retrieves a list of all parliaments',
        'file' => array('file' => 'inc', 'module' => 'pw_api'),
        'callback' => 'pw_api_parliament_index',
        'access callback' => 'user_access',
        'access arguments' => array('access content'),
        'access arguments append' => FALSE,
      ),
    ),
  );
}
