<?php

/**
 * Implementation of hook_menu
 */

function rate_voteas_menu(){
  
  $items['node/%node/rating-voteas'] = array(
    'title' => 'Manipulate Voting results',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('rate_voteas_voting_form',1),
    'access arguments' => TRUE,
    'type' => MENU_LOCAL_TASK,
    'weight' => 10,
    'file' => 'rate_voteas.page.inc',
  );
  
  return $items;
}

/**
 * implementation of hook_perm
 */

function rate_voteas_perm(){
  return array(
    'rate_voteas voting' => array(
      'title' => t('Vote as User'), 
      'description' => t('Allows to vote as a certain user.'),
    ),
  );
}
